import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ReduxProvider from "@/utils/redux/reduxProvider";
import { Roboto, Spline_Sans_Mono } from "next/font/google";
import "./globals.css";
const sansMono = Spline_Sans_Mono({
  weight: ["400", "400"],
  subsets: ["latin"]
})

const roboto = Roboto({
  weight: ["400", "400"],
  subsets: ["latin"]
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={` ${roboto.className} ${sansMono.className} antialiased`}
      >
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
